### ISSUE TITLE
Plugin fails with Gradle 4.x

### ISSUE THREAD

**Issue by manuelprinz** [coditory/gradle-integration-test-plugin#1]
First of all: Thanks for the nice plug-in! :+1: 

This is more of a question than an issue: I am very interested in using your plug-in to get rid of boilerplate code. Unfortunately, it seems that the plug-in uses some Gradle 5 APIs that make it fail on Gradle 4.x. It would be really great if the plug-in worked on the older version also. Do you have any plans to support that?

**Comment by pmendelski** [comment]
Thank for using this plugin and submitting issue.

I added compatibility with gradle v4.x ([tested on 4.9](https://github.com/coditory/gradle-integration-test-plugin/blob/098bbb17f5dd56919a9a1fb8db73fc149ee8984a/src/test/kotlin/com/coditory/gradle/integration/SpockBasedAcceptanceSpec.kt#L92)). Please update to version `1.0.6` and let me know if all is good.

**Comment by pmendelski** [comment]
Fixed in version 1.0.6 commit https://github.com/coditory/gradle-integration-test-plugin/commit/098bbb17f5dd56919a9a1fb8db73fc149ee8984a

**Comment by manuelprinz** [comment]
Thank you for the quick fix! Tested on 4.8, works like a charm!
