### ISSUE TITLE
Lombok doesn't work out-of-box

### ISSUE THREAD

**Issue by sokada1221** [coditory/gradle-integration-test-plugin#10]
Currently the plugin doesn't support `testCompileOnly` and `testAnnotationProcessor` keywords, which is needed for the Lombok library.

Snippet from https://projectlombok.org/setup/gradle
```
dependencies {
	compileOnly 'org.projectlombok:lombok:1.18.20'
	annotationProcessor 'org.projectlombok:lombok:1.18.20'
	
	testCompileOnly 'org.projectlombok:lombok:1.18.20'
	testAnnotationProcessor 'org.projectlombok:lombok:1.18.20'
}
```

Workaround is to specifically add the dependencies for the integration test. For example:
```
dependencies {
	integrationCompileOnly 'org.projectlombok:lombok:1.18.20'
	integrationAnnotationProcessor 'org.projectlombok:lombok:1.18.20'
}
```

Since Lombok library is fairly popular and can be useful for integration tests, it'd be nice to support it.

**Comment by pmendelski** [comment]
Hi, thanks for your PR.

I extended all test configurations to handle all cases like the one with Lombok ([commit](https://github.com/coditory/gradle-integration-test-plugin/commit/cd0c3cae40ac53592c4f5ecd3b15fa184302bde3)). Please, try version `1.3.0` and let me know if all is good.

**Comment by sokada1221** [comment]
Verified that v1.3.0 works fine. Thanks.
