### ISSUE TITLE
Env var parameter?

### ISSUE THREAD

**Issue by aecc** [coditory/gradle-integration-test-plugin#12]
Hi. How can I pass a parameter from gradle itself that later on is passed to the integration tests?
i.e.:

./gradlew -i -Pconfig.file=test_config.yml integrationTest

so later on in my java integration test can be read using:

System.getProperty("config.file", "dev_config.yml")

Any advice? Regards

**Comment by pmendelski** [comment]
Hi, how about simply using [`System.getenv("MY_ENV_VAR")`](https://www.baeldung.com/java-system-get-property-vs-system-getenv#using-systemgetenv) ?
