### ISSUE TITLE
Migrate to test suites Gradle plugin

### ISSUE THREAD

**Issue by bgalek** [coditory/gradle-integration-test-plugin#126]
Should this plugin switch to Gradle test suites? 

https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html#configure_dependencies_of_a_test_suite_to_reference_project_outputs

**Comment by pmendelski** [comment]
Definitely it should.

I hoped to see it mature from incubation first (from the same [docs](https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html): `The JVM Test Suite plugin is an incubating API and is subject to change in a future release.`) but am willing to merge a change :)

The minimal supported gradle version in gradle-integration-test-plugin was [recently upgraded](https://github.com/coditory/gradle-integration-test-plugin/commit/2300e387675a203f6f75df75c3ffe1745f284b3e#diff-185860cb926efa70df2c3c0b02543626ac728f2459316c0d558323bb0cd1647dL167) so I it should be easier now.
