### ISSUE TITLE
Idea support - integration srcset marked as test source

### ISSUE THREAD

**Issue by bgalek** [coditory/gradle-integration-test-plugin#127]
Since there is a known workaround for marking the integration directory as a test source with kotlin internal classes working (without explicitly using the idea plugin), maybe it's time to support this feature again? :)

https://github.com/sdkotlin/sd-kotlin-talks/commit/a8a6996a65b4da839ffc4cb270fe923174b0fc88

**Comment by pmendelski** [comment]
Thanks for the link, sounds interesting. It requires migrating to test suites first https://github.com/coditory/gradle-integration-test-plugin/issues/126.

I will probably test it in the near future but cannot provide any timeline. Would you like to do it yourself?

**Comment by bgalek** [comment]
Sure thing, I'll be happy to try, but don't wait for me if you find time yourself ;)

**Comment by pmendelski** [comment]
Hey @bgalek, take a look at release [2.0.0](https://github.com/coditory/gradle-integration-test-plugin/releases/tag/v2.0.0).
New release integrates with Jvm Test Suites and Jacoco, but look out for some backward incompatibilities.

**Comment by bgalek** [comment]
Nice, but...

`src/integration` rename to `src/integrationTest` is going to cause a lot of havoc, since dependabot will update it and build will be passing, just less tests would be run... 

At least at my organization.

**Comment by pmendelski** [comment]
I changed it because having different source name `integration` and task name `integrationTest` is cumbersome in JVM test Suites.

The plugin could simply fail builds if `src/integration` is detected ...but for now I created a walk-around with some mapping so the change is less problematic.   https://github.com/coditory/gradle-integration-test-plugin/pull/141

Let me know if that plays for you

**Comment by pmendelski** [comment]
Released as 2.0.1

**Comment by bgalek** [comment]
Thank you, I think it will be ok now :)

**Comment by pmendelski** [comment]
Cool and you're welcome.

BTW, 10k repos using this plugin and only 61 stars submitted. That's outrageous 😜

**Comment by bgalek** [comment]
@pmendelski I'll take care of this on Wendsday on Hacktoberfest event <3
