### ISSUE TITLE
JDK11 Support

### ISSUE THREAD

**Issue by bgalek** [coditory/gradle-integration-test-plugin#142]
Hi again @pmendelski! 
Don't get me wrong - I love to have bleeding edge JDK runtime in my projects, but....
...since JDK11 is still considered a LTS I think it would be nice to compile by JDK11 not JDK17 by default https://github.com/coditory/gradle-integration-test-plugin/blob/main/build.gradle.kts#L32 ;)
WDYT?

**Comment by pmendelski** [comment]
Hello there!

Am I misreading something?

Both sources:
- https://www.oracle.com/java/technologies/java-se-support-roadmap.html
- https://endoflife.date/oracle-jdk

state that JDK11 is in deed a LTS version but the Premiere Support has ended ~1y ago.
If you're looking at Extended Support I should compile for JDK 8 - which is a stone age version ;)

**Comment by bgalek** [comment]
Hm... You're right :) maybe it's about time to push to 17 a bit harder :)
