### ISSUE TITLE
Readme: gradle plugin badge hardcoded with 1.5.0 :)

### ISSUE THREAD

**Issue by bgalek** [coditory/gradle-integration-test-plugin#152]
in `README.md` you have:
```
[![Gradle Plugin Portal](https://img.shields.io/badge/Plugin_Portal-v1.5.0-green.svg)](https://plugins.gradle.org/plugin/com.coditory.integration-test)
```
[![Gradle Plugin Portal](https://img.shields.io/badge/Plugin_Portal-v1.5.0-green.svg)](https://plugins.gradle.org/plugin/com.coditory.integration-test)
it has v1.5.0 hardcoded ;)

##  Fix

Go with: 
```
![Gradle Plugin Portal Version](https://img.shields.io/gradle-plugin-portal/v/com.coditory.integration-test)
```
![Gradle Plugin Portal Version](https://img.shields.io/gradle-plugin-portal/v/com.coditory.integration-test)

**Comment by pmendelski** [comment]
Good point :)

The version should be updated by the [release script](https://github.com/coditory/workflows/blob/main/.github/workflows/release.yml#L185), but automatic badge is better, thanks.
