### ISSUE TITLE
integrationTest+Junit5: test cases didn't triggered

### ISSUE THREAD

**Issue by manavsah** [coditory/gradle-integration-test-plugin#2]
Hi All, 
i added 
plugins {
...
  id 'com.coditory.integration-test' version '1.1.2' //
}
dependencies {
...
 testImplementation "io.vertx:vertx-junit5:$vertxVersion"
  testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junitJupiterEngineVersion"
  testImplementation "org.junit.jupiter:junit-jupiter-api:$junitJupiterEngineVersion"
}
to my gradle project.

with above configuration i was not able to run my tests @ path "<PRJ>/src/integration/java".
-----------------------------------------------
> Task :compileJava
> Task :processResources
> Task :classes
> Task :jar
> Task :compileTestFixturesJava NO-SOURCE
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses
> Task :compileIntegrationJava
> Task :processIntegrationResources NO-SOURCE
> Task :integrationClasses
> Task :processTestFixturesResources NO-SOURCE
> Task :testFixturesClasses UP-TO-DATE
> Task :testFixturesJar
> Task :integrationTest
BUILD SUCCESSFUL in 1s

***** No tests executed.**

----------------------
To make it run i need to add
integrationTest.doFirst {
  useJUnitPlatform()
}

> Task :testFixturesJar
> Task :integrationTest
HTTP server started on port 8888
BUILD SUCCESSFUL in 3s
10 actionable tasks: 9 executed, 1 up-to-date
2:53:30 AM: Task execution finished 'integrationTest'.

Thanks
Manav

**Comment by pmendelski** [comment]
Hi @manavsah ,

Thanks for submitting your issue.
I've updated configuration so the plugin integrates better with JUnit5.
Please update your plugin version to `v1.1.6` and your `build.gradle` as in [the sample project](https://github.com/coditory/gradle-integration-test-plugin-sample/blob/master/java-junit5/build.gradle).

Thanks,
Paweł
