### ISSUE TITLE
IntelliJ IDEA does not mark integration source sets as "Test Sources"

### ISSUE THREAD

**Issue by kota65535** [coditory/gradle-integration-test-plugin#3]
The added integration source sets are marked as "Sources".
![image](https://user-images.githubusercontent.com/10975834/89097281-90b05400-d418-11ea-800d-ba9b2c58beeb.png)

I confirmed that putting the following snippet in my build.gradle makes it mark as "Test Sources", as directed in this comment: https://youtrack.jetbrains.com/issue/IDEA-151925#focus=Comments-27-2355076.0-0
```
apply plugin: 'idea'
idea {
    module {
        testSourceDirs += project.sourceSets.integration.java.srcDirs
        testSourceDirs += project.sourceSets.integration.resources.srcDirs
    }
}
```

Including this configuration above in the plugin is really helpful.

**Comment by pmendelski** [comment]
Hi, thanks for the snippet.
I've just released it with new version `1.1.8`.

Please let me know if it covers all of your use cases.

How does it work?
- The plugin applies `IdeaPlugin` if there is `.idea` folder in rootProject directory. 
- When `IdeaPlugin` plugin is detected, `integration` directories are added to idea module testDirs

**Comment by kota65535** [comment]
Hi @pmendelski, It works perfectly! Now the integration folder is marked as "Test Sources" and I completely deleted the snippet applying idea plugin from my build.gradle. Thank you for your quick response!

**Comment by kota65535** [comment]
Hi @pmendelski, I've read issue #26 about disabling IdeaPlugin.
Instead of completely disabling it, how about adding a configuration to toggle the feature?
This feature is very important for me since whether the folder is "Sources" or "Test Sources" affects the behavior of SonarLint plugin.

**Comment by kota65535** [comment]
Not stale

**Comment by kota65535** [comment]
Not stale

**Comment by kota65535** [comment]
Not stale
