### ISSUE TITLE
IntelliJ shows warning on integration test methods with whitespaces

### ISSUE THREAD

**Issue by simonhauck** [coditory/gradle-integration-test-plugin#30]
Hello,

First of all, I love to use your plugin, since it eliminates any configuration. 

After upgrading to the latest version (1.4.4), test methods in the integration package and whitespaces in the name are marked with a warning in IntelliJ (as shown in the image), but this is a valid syntax in test packages [Link](https://kotlinlang.org/docs/coding-conventions.html#names-for-test-methods).

![image](https://user-images.githubusercontent.com/29832799/206993463-0b43e285-01a1-4f1a-ab2e-c0cdc8f3c0fa.png)

In the previous version this worked as expected without a warning and might be linked to #26.

Is this the intended behavior or a bug? And as a follow up question, are there any workarounds?

**Comment by pmendelski** [comment]
Hi, thanks for the kind words :gift: 

The reasoning for dropping support for Idea Plugin you can find in this issue https://github.com/coditory/gradle-integration-test-plugin/issues/26. In short, it was a trade-off.

The underlined method name is not an invalid syntax. It's just an IDE default checkstyle rule. You can workaround it by simply hiding the inspection. Click on "More actions..." (link visible on your screenshot), and then three dots next to "Rename" and "Disable inspection".

![Screenshot from 2022-12-13 00-45-15](https://user-images.githubusercontent.com/719718/207184513-a938411c-295c-47cb-bb8a-1e08012773ae.png)

Hope it helps, cheers
