### ISSUE TITLE
Gradle 7 support

### ISSUE THREAD

**Issue by rethab** [coditory/gradle-integration-test-plugin#4]
I have upgraded to gradle 7.0-rc1 and I'm getting errors, like: "Entry myfile.csv is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.0-rc-1/dsl/org.gradle.api.file.CopySpec.html#org.gradle.api.file.CopySpec:duplicatesStrategy for details."

This file is in the resources directory of the integration folder. I can't tell for sure, but I suspect this plugin might not work with gradle 7? Of course gradle 7 is not released yet, but just wanted to check whether you think this could be the issue?

The reason I suspect this plugin is that I read in [1] that it happens when using the standard source sets and I see in [2] something that might cause it?
1. https://github.com/gradle/gradle/issues/13578#issuecomment-659055952
2. https://github.com/coditory/gradle-integration-test-plugin/blob/master/src/main/kotlin/com/coditory/gradle/integration/IntegrationTestTaskConfiguration.kt#L21

**Comment by pmendelski** [comment]
Hi,

I've just released version 1.2.0 with support for gradle 7.
Please let me know if it works for your case.

**Comment by rethab** [comment]
Yes it does! :tada: 

Thanks a lot!
